package dropbox

import (
	"fmt"
	"github.com/labstack/echo/v4"
	"io/ioutil"
	"net/http"
	"strings"
	"time"
)

// Service contains the necessary data to access a dropbox.
type Service struct {
	token         string
	rootDirectory string
}

// New returns a new dropbox service.
//
// The token is either generated by the normal OAuth2 workflow from
// dropbox or a token manually generated using the app console for your
// specific application.
//
// The rootDirectory is the root for all accessed files.
func New(token string, rootDirectory string) *Service {
	if !strings.HasSuffix(rootDirectory, "/") {
		rootDirectory = rootDirectory + "/"
	}

	return &Service{
		token:         token,
		rootDirectory: rootDirectory,
	}
}

// Read downloads the requested file from dropbox.
//
// I'm still not happy that the echo logger interface is polluting our
// dropbox service instead of a more general (log) or custom (zerolog)
// interface. Of course, I could write a wrapper back from lecho to
// zerolog, but this is a lot of work for this small program, hence 🤷‍.
// Although I miss zerlog's context, e.g. for filenames.
func (s *Service) Read(log echo.Logger, filename string) ([]byte, error) {
	start := time.Now()

	// Create request.
	client := http.Client{}
	request, err := http.NewRequest("POST", "https://content.dropboxapi.com/2/files/download", nil)
	if err != nil {
		return nil, fmt.Errorf("unable to create request: %s", err)
	}
	argument := fmt.Sprintf(`{"path": "/%s%s"}`, s.rootDirectory, filename)
	request.Header.Add("Authorization", "Bearer "+s.token)
	request.Header.Add("Dropbox-API-Arg", argument)

	// Execute request.
	resp, err := client.Do(request)
	if err != nil {
		return nil, fmt.Errorf("unable to perform request: %s", err)
	}
	defer resp.Body.Close()

	// Read file content.
	bs, err := ioutil.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("unable to read data from response: %s", err)
	}
	if resp.StatusCode != 200 {
		return nil, fmt.Errorf("non 200 response from dropbox: `%s`", string(bs))
	}

	// Return data and log elapsed time.
	elapsed := time.Since(start)
	log.Infof("Read file from dropbox. filename=%s, duration=%v", filename, elapsed.Milliseconds())
	return bs, err
}
