name: Build, Push and Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Build and push Docker
      uses: docker/build-push-action@v1.1.0
      with:
        registry: ghcr.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: mlesniak/markdown
        tags: latest
        build_args: |
          COMMIT: ${{ github.sha }}

    - name: Pull, stop and restart
      uses: alinz/ssh-scp-action@master
      with:
        key: ${{ secrets.PRIVATE_KEY }}
        host: mlesniak.com
        port: 22
        user: ${{ secrets.USERNAME}}
        # runs this on remote server
        ssh_before: |
          docker pull ghcr.io/mlesniak/markdown:latest
          docker rm --force markdown
          docker run -d --name markdown --env-file markdown.env -v /root/download:/data/download -it -p 8088:8080 ghcr.io/mlesniak/markdown:latest

